# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64, verbose_name='Автор')),
                ('email_author', models.EmailField(max_length=254, verbose_name='Email адрес')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('approved', models.BooleanField(default=False, verbose_name='Подтвержден?')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата комментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Article')),
            ],
            options={
                'verbose_name_plural': 'комментарии',
                'verbose_name': 'комментарий',
            },
        ),
    ]
