# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_meta', models.CharField(blank=True, max_length=80, null=True)),
                ('description_meta', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('short_post', models.TextField(verbose_name='Краткое описание')),
                ('full_post', models.TextField(db_index=True, verbose_name='Полное описание')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Статьи',
                'verbose_name': 'Статья',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_meta', models.CharField(blank=True, max_length=80, null=True)),
                ('description_meta', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.URLField(blank=True, null=True, verbose_name='Адрес к иконке')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='posts.Category', verbose_name='Категория'),
        ),
    ]
