# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:41
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170422_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
