# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170423_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='full_post',
            field=models.TextField(verbose_name='Полное описание'),
        ),
    ]
