# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170424_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prefix_slug',
            field=models.SlugField(blank=True),
        ),
    ]
